name: gnutls-ubuntu-x64

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-openssl:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
            apt-get install -y dash git-core autoconf libtool gettext autopoint
            apt-get install -y automake python3 nettle-dev libp11-kit-dev libtspi-dev libunistring-dev
            apt-get install -y libtasn1-bin libtasn1-6-dev libidn2-0-dev gawk gperf
            apt-get install -y libtss2-dev libunbound-dev dns-root-data bison gtk-doc-tools
            apt-get install -y texinfo texlive texlive-plain-generic texlive-extra-utils


      - name: Clone Project
        run: |
          git clone https://gitlab.com/gnutls/gnutls.git
  

      - name: Configure and Build
        run: |
          cd gnutls
          ./bootstrap
          ./configure

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gnutls-ubuntu-x64
          path: gnutls/  # Adjust if you only want specific output files
