name: gnutls-ubuntu-x64

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-openssl:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y dash git-core autoconf libtool gettext autopoint libev4t64
            sudo apt install -y automake python3 nettle-dev libp11-kit-dev libtspi-dev libunistring-dev
            sudo apt install -y libtasn1-bin libtasn1-6-dev libidn2-0-dev gawk gperf
            sudo apt install -y libtss2-dev libunbound-dev dns-root-data bison gtk-doc-tools
            sudo apt install -y texinfo texlive texlive-plain-generic texlive-extra-utils


      - name: Clone Project
        run: |
          git clone https://gitlab.com/gnutls/gnutls.git
  

      - name: Configure and Build
        run: |
          cd gnutls
          ./bootstrap
          ./configure --prefix=$PWD/../build
          make -j$(nproc)
          make install

      - name: Create tar.xz archive
        run: |
          tar -cJf openssl-ubuntu-x86_64.tar.xz -C gnutls .

      - name: Upload OpenSSL build archive
        uses: actions/upload-artifact@v4
        with:
          name: openssl-ubuntu-x86_64
          path: openssl-ubuntu-x86_64.tar.xz
