name: Build OpenSSL

on:
  workflow_dispatch:

jobs:
  build-openssl:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential perl git

      - name: Clone OpenSSL
        run: |
          git clone https://github.com/openssl/openssl.git

      - name: Configure, Build, and Install
        run: |
          cd openssl
          ./config --prefix=$PWD/../build --openssldir=$PWD/../build/ssl
          make -j$(nproc)
          make install

      - name: Print build directory structure
        run: ls -alR build/

      - name: Upload OpenSSL build output
        uses: actions/upload-artifact@v4
        with:
          name: openssl-build
          path: build/
