name: ubuntu-zig-x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zig:
    runs-on: ubuntu-latest

    steps:

      - name: Clone the script
        run: |
          git clone https://github.com/CodeOfSomnath/library-builds.git

      - name: Configure and Build
        run: |
          cd library-builds
          sudo apt update
          sudo apt install python3
          sudo python3 zig.py -o bin

      - name: Create tar.xz archive
        run: |
          tar -cJf zig-ubuntu-x86_64-11042025.tar.xz -C library-builds/zig/bin .

      - name: Upload GnuTLS build archive
        uses: actions/upload-artifact@v4
        with:
          name: zig-ubuntu-x86_64-11042025
          path: zig-ubuntu-x86_64-11042025.tar.xz