name: ubuntu-x86_64

on:
  workflow_dispatch:

jobs:
  openssl:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential perl git

      - name: Clone OpenSSL
        run: |
          git clone https://github.com/openssl/openssl.git

      - name: Configure, Build, and Install
        run: |
          cd openssl
          ./config --prefix=$PWD/../build --openssldir=$PWD/../build/ssl
          make -j$(nproc)
          make install

      - name: Print build directory structure
        run: ls -alR build/

      - name: Create tar.xz archive
        run: |
          tar -cJf openssl-ubuntu-x86_64-08042025.tar.xz -C build .

      - name: Upload OpenSSL build archive
        uses: actions/upload-artifact@v4
        with:
          name: openssl-ubuntu-x86_64-08042025
          path: openssl-ubuntu-x86_64-08042025.tar.xz

  gnutls:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y libev4 libev-dev
            sudo apt install -y dash git-core autoconf libtool gettext autopoint 
            sudo apt install -y automake python3 nettle-dev libp11-kit-dev libtspi-dev libunistring-dev
            sudo apt install -y libtasn1-bin libtasn1-6-dev libidn2-0-dev gawk gperf
            sudo apt install -y libtss2-dev libunbound-dev dns-root-data bison gtk-doc-tools
            sudo apt install -y texinfo texlive texlive-plain-generic texlive-extra-utils


      - name: Clone Project
        run: |
          git clone https://gitlab.com/gnutls/gnutls.git
  

      - name: Configure and Build
        run: |
          cd gnutls
          ./bootstrap
          ./configure --prefix=$PWD/../build
          make -j$(nproc)
          make install

      - name: Create tar.xz archive
        run: |
          tar -cJf gnutls-ubuntu-x86_64-08042025.tar.xz -C build .

      - name: Upload GnuTLS build archive
        uses: actions/upload-artifact@v4
        with:
          name: gnutls-ubuntu-x86_64-08042025
          path: gnutls-ubuntu-x86_64-08042025.tar.xz

  zig:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y cmake build-essential git gdb
            sudo apt install -y clang libclang-dev llvm liblld-dev


      - name: Clone Project
        run: |
          git clone https://github.com/ziglang/zig.git
  

      - name: Configure and Build
        run: |
          cd zig
          mkdir build
          mkdir bin
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$(pwd)/bin
          cd build
          make
          make install

      - name: Create tar.xz archive
        run: |
          tar -cJf zig-ubuntu-x86_64-08042025.tar.xz -C bin .

      - name: Upload GnuTLS build archive
        uses: actions/upload-artifact@v4
        with:
          name: zig-ubuntu-x86_64-08042025
          path: zig-ubuntu-x86_64-08042025.tar.xz

  llvm:
    runs-on: ubuntu-latest

    steps:

      - name: Clone the script
        run: |
            git clone https://github.com/CodeOfSomnath/library-builds.git

      - name: Build project
        run: |
            cd library-builds
            sudo apt update
            sudo apt install python3
            sudo python3 llvm.py -o bin

      - name: Create tar.xz archive
        run: |
          cd llvm-project
          tar -cJf llvm-ubuntu-x86_64-08042025.tar.xz -C bin .

      - name: Upload GnuTLS build archive
        uses: actions/upload-artifact@v4
        with:
          name: llvm-ubuntu-x86_64-08042025
          path: llvm-ubuntu-x86_64-08042025.tar.xz